[Ubuntu/post-install] local variables are now lower case Added `gh` (GitHub Cli) installation via apt repo in linux and via homebrew in MacOS

diff --git a/Ubuntu/post-install b/Ubuntu/post-install
--- a/Ubuntu/post-install
+++ b/Ubuntu/post-install
@@ -10,50 +10,69 @@ strictMode
 # shellcheck disable=SC1091
 . "${GITROOT}"/Ubuntu/base
 
+export TMP_DOT_FILES
+TMP_DOT_FILES=$(mktemp -d dot-files.XXXX)
+
+function cleanup() {
+  echo "Deleting ${TMP_DOT_FILES}"
+  rm -rf "${TMP_DOT_FILES}"
+}
+# Make sure cleanup runs even if this script fails
+trap cleanup EXIT
+
 function get_deb_url_from_xpath() {
-  local URL="${1}"
-  local XPATH="${2}"
-  local DEB_URL
-  DEB_URL="$(curl -s \
-      "${URL}" | \
+  local url="${1}"
+  local xpath="${2}"
+  local deb_url
+  deb_url="$(curl -s \
+      "${url}" | \
       xmllint --html \
-      --xpath "${XPATH}" - 2> /dev/null)"
-  if [[ "${#DEB_URL}" -lt 4 ]]; then
+      --xpath "${xpath}" - 2> /dev/null)"
+  if [[ "${#deb_url}" -lt 4 ]]; then
     return 1
   fi
-  echo "${DEB_URL}"
+  echo "${deb_url}"
 }
 
 function is_repo_present() {
-  local REPO="${1}"
-  grep -v -E '^#|^ *$' /etc/apt/sources.list /etc/apt/sources.list.d/*.list | grep -Fq "${REPO/ppa:/}"
+  local repo="${1}"
+  grep -v -E '^#|^ *$' /etc/apt/sources.list /etc/apt/sources.list.d/*.list | grep -Fq "${repo/ppa:/}"
 }
 
 function add_apt_repo() {
-  local REPO="${1}"
-  local FILE_NAME="${2}"
-  msg_info "will try to remove repository ${REPO} if it exists already"
-  if ! is_repo_present "${REPO}"; then
-    if [[ "${REPO}" =~ ^ppa:.*/ppa$ ]]; then
-      sudo add-apt-repository -y "${REPO}"
+  local repo="${1}"
+  local file_name="${2}"
+  msg_info "will try to remove repository ${repo} if it exists already"
+  if ! is_repo_present "${repo}"; then
+    if [[ "${repo}" =~ ^ppa:.*/ppa$ ]]; then
+      sudo add-apt-repository -y "${repo}"
     else
-      echo "${REPO}" | sudo tee /etc/apt/sources.list.d/"${FILE_NAME}".list > /dev/null
+      echo "${repo}" | sudo tee /etc/apt/sources.list.d/"${file_name}".list > /dev/null
     fi
   fi
 }
 
 function add_apt_key() {
-  local URL="${1}"
-  local KEY_NAME="${2}"
-  local TMP_DOT_FILES="${3}"
-  local FILE_NAME="${TMP_DOT_FILES}/${KEY_NAME}.gpg"
-  msg_info "Working on apt_key ${KEY_NAME}"
-  curl -fsSL "${URL}" | gpg --dearmor > "${FILE_NAME}"
-  sudo install -o root -g root -m 644 "${FILE_NAME}" /etc/apt/trusted.gpg.d/
+  local url="${1}"
+  local key_name="${2}"
+  local file_name="${TMP_DOT_FILES}/${key_name}.gpg"
+  msg_info "Working on apt_key ${key_name}"
+  curl -fsSL "${url}" | gpg --dearmor > "${file_name}"
+  sudo install -o root -g root -m 644 "${file_name}" /etc/apt/trusted.gpg.d/
+}
+
+function store_key() {
+  local url="${1}"
+  local file_name="${2}"
+  local full_path="/etc/apt/keyrings/${file_name}"
+  msg_info "Working on keyring ${key_name}"
+  sudo curl -fsSL "${url}" -o "${full_path}"
+  sudo chmod a+r "${full_path}"
+  msg_info "Created ${full_path}"
 }
 
 function are_extra_cli_tools_installed() {
-  declare -a EXTRA_CLI_TOOLS=('bash-completion'
+  declare -a extra_cli_tools=('bash-completion'
     'ca-certificates'
     'cmake'
     'libcurl4'
@@ -64,11 +83,13 @@ function are_extra_cli_tools_installed() {
     'pandoc'
     'pkg-config'
     'tshark')
-  install_if_not_installed 'apt' 'n' "${EXTRA_CLI_TOOLS[@]}"
+  install_if_not_installed 'apt' 'n' "${extra_cli_tools[@]}"
 }
 
 function are_extra_tools_installed() {
-  declare -a EXTRA_UBUNTU_TOOLS=('ghostwriter'
+  declare -a extra_ubuntu_tools=(
+    'gh'
+    'ghostwriter'
     'network-manager-openvpn-gnome'
     'openvpn-systemd-resolved'
     'pinta'
@@ -79,8 +100,9 @@ function are_extra_tools_installed() {
     'wezterm'
     'wireguard'
     'wireshark-gtk')
-  install_if_not_installed 'apt' 'n' "${EXTRA_UBUNTU_TOOLS[@]}"
-  declare -a EXTRA_BREW_TOOLS=('bat'
+  install_if_not_installed 'apt' 'n' "${extra_ubuntu_tools[@]}"
+  declare -a extra_brew_tools=(
+    'bat'
     'bfg'
     'fd'
     'fpp'
@@ -90,84 +112,83 @@ function are_extra_tools_installed() {
     'shfmt'
     'termshark'
     'tmux')
-  install_if_not_installed 'brew' 'n' "${EXTRA_BREW_TOOLS[@]}"
+  install_if_not_installed 'brew' 'n' "${extra_brew_tools[@]}"
 }
-
 
 function is_docker_installed() {
   if [[ ! -x $(command -v docker) ]]; then
-    declare -a DOCKER_DEPS=('apt-transport-https'
+    declare -a docker_deps=('apt-transport-https'
       'ca-certificates'
       'curl'
       'gnupg-agent')
-    install_if_not_installed 'apt' 'n' "${DOCKER_DEPS[@]}"
+    install_if_not_installed 'apt' 'n' "${docker_deps[@]}"
     sudo apt -y install docker-ce docker-ce-cli containerd.io
   fi
 }
 
-
 function download_and_install_deb() {
-  local DEB_URL="${1}"
-  local DEB_NAME="${2}"
-  local DEB_FILE_NAME="${DEB_NAME}.deb"
+  local deb_url="${1}"
+  local deb_name="${2}"
+  local deb_file_name="${deb_name}.deb"
+  local file_name="${TMP_DOT_FILES}/${deb_file_name}"
 
-  if ! grep -q "${DEB_NAME}" <(sudo apt list --installed 2> /dev/null); then
-    msg_info "Will download and install ${DEB_NAME}"
-    curl -Lv "${DEB_URL}" -o "${DEB_FILE_NAME}"
-    sudo apt install -y "./${DEB_FILE_NAME}"
-    rm "${DEB_FILE_NAME}"
+  if ! grep -q "${deb_name}" <(sudo apt list --installed 2> /dev/null); then
+    msg_info "Will download and install ${deb_name}"
+    curl -Lv "${deb_url}" -o "${file_name}"
+    sudo apt install -y "${file_name}"
   else
-    msg_info "${DEB_NAME} is installed already"
+    msg_info "${deb_name} is installed already"
   fi
 }
 
 function install_desktop_apps() {
-  local TMP_DOT_FILES
-  TMP_DOT_FILES=$(mktemp -d dot-files.XXXX)
-
   msg_info 'Adding apt keys for docker, sublime-text'
-  declare -A APT_KEYS=(
+  declare -A apt_keys=(
     ['sublime']='https://download.sublimetext.com/sublimehq-pub.gpg'
     ['wezterm-fury']='https://apt.fury.io/wez/gpg.key'
   )
 
-  for KEY_NAME in "${!APT_KEYS[@]}"; do
-    add_apt_key "${APT_KEYS[${KEY_NAME}]}" "${KEY_NAME}" "${TMP_DOT_FILES}"
+  for key_name in "${!apt_keys[@]}"; do
+    add_apt_key "${apt_keys[${key_name}]}" "${key_name}"
   done
 
-  msg_info 'Will create /etc/apt/keyrings/docker.asc if does not exist'
-  if [[ ! -e /etc/apt/keyrings/docker.asc ]]; then
-    sudo install -m 0755 -d /etc/apt/keyrings
-    sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
-    sudo chmod a+r /etc/apt/keyrings/docker.asc
-    msg_info 'Created /etc/apt/keyrings/docker.asc'
-  fi
+  declare -A keyrings=(
+    ['docker.asc']='https://download.docker.com/linux/ubuntu/gpg'
+    ['githubcli-archive-keyring.gpg']='https://cli.github.com/packages/githubcli-archive-keyring.gpg'
+  )
+
+  sudo install -m 0755 -d /etc/apt/keyrings
+  for keyring in "${!keyrings[@]}"; do
+    store_key "${keyrings[${keyring}]}" "${keyring}"
+  done
 
   echo "Adding repositories: docker, GhostWriter, sublime-text"
-  declare -A REPOSITORIES=(
+  declare -A repositories=(
     ['docker']="deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
+    ['github-cli']="deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
     ['ghostwriter']='ppa:wereturtle/ppa'
     ['ubuntu-cleaner']='ppa:gerardpuig/ppa'
     ['sublime']='deb [signed-by=/etc/apt/trusted.gpg.d/sublime.gpg] https://download.sublimetext.com/ apt/stable/'
     ['wezterm']='deb [signed-by=/etc/apt/trusted.gpg.d/wezterm-fury.gpg] https://apt.fury.io/wez/ * *'
   )
 
-  for KEY in "${!REPOSITORIES[@]}"; do
-    add_apt_repo "${REPOSITORIES[${KEY}]}" "${KEY}"
+  for key in "${!repositories[@]}"; do
+    add_apt_repo "${repositories[${key}]}" "${key}"
   done
 
   echo "Installing Google Chrome Stable, Slack"
-  LATEST_SLACK="$(get_deb_url_from_xpath 'https://slack.com/downloads/instructions/linux?ddl=1&build=deb' 'string(/html/body/main/section[1]/iframe/@src)')"
-  declare -A DEB_PACKAGES=(
+  local latest_slack
+  latest_slack="$(get_deb_url_from_xpath 'https://slack.com/downloads/instructions/linux?ddl=1&build=deb' 'string(/html/body/main/section[1]/iframe/@src)')"
+  declare -A deb_packages=(
     ['1password']='https://downloads.1password.com/linux/debian/amd64/stable/1password-latest.deb' # pragma: allowlist secret
     ['google-chrome-stable']='https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb'
-    ['slack']="${LATEST_SLACK}"
+    ['slack']="${latest_slack}"
     ['nala']='https://deb.volian.org/volian/pool/main/v/volian-archive/volian-archive-nala_0.3.1_all.deb'
     ['volian-keyring']='https://deb.volian.org/volian/pool/main/v/volian-archive/volian-archive-keyring_0.3.1_all.deb'
   )
 
-  for KEY in "${!DEB_PACKAGES[@]}"; do
-    download_and_install_deb "${DEB_PACKAGES[${KEY}]}" "${KEY}"
+  for key in "${!deb_packages[@]}"; do
+    download_and_install_deb "${deb_packages[${key}]}" "${key}"
   done
 
   retry_command "10" "sudo" "apt" "update"
@@ -177,7 +198,8 @@ function install_desktop_apps() {
 
   # needed for multiple apps
   mkdir -p "${HOME}/bin" || true
-  HOME_BIN="${HOME}/bin"
+  local home_bin
+  home_bin="${HOME}/bin"
 
   if ! grep -q 'JetBrains Mono' <(fc-list); then
     echo 'Installing Jetbrains Font'
@@ -198,19 +220,21 @@ function install_desktop_apps() {
 
   if ! piactl --version &>/dev/null; then
     echo "Installing Private Internet Access"
-    LATEST_PIA_INSTALLER=$(curl \
+    local latest_pia_installer
+    latest_pia_installer=$(curl \
         'https://www.privateinternetaccess.com/installer/x/download_installer_linux' | \
         xmllint --html --xpath '//html/head/meta[5]/@content' - 2> /dev/null | cut -d '"' -f2 | cut -d '=' -f2)
-    curl -Lv "${LATEST_PIA_INSTALLER}" -o "${TMP_DOT_FILES}/pia-linux.run"
+    curl -Lv "${latest_pia_installer}" -o "${TMP_DOT_FILES}/pia-linux.run"
     sh "${TMP_DOT_FILES}/pia-linux.run"
   fi
 
   if ! jetbrains-toolbox --version &>/dev/null; then
     echo "Installing JetBrains Toolbox"
-    LATEST_JETBRAINS_TOOLBOX=$(curl -sL 'https://data.services.jetbrains.com//products/releases?code=TBA&latest=true&type=release' | jq -r '.TBA[].downloads.linux.link')
-    curl -Lv "${LATEST_JETBRAINS_TOOLBOX}" -o "${TMP_DOT_FILES}/jetbrains-toolbox.tar.gz"
+    local latest_jetbrains_toolbox
+    latest_jetbrains_toolbox=$(curl -sL 'https://data.services.jetbrains.com//products/releases?code=TBA&latest=true&type=release' | jq -r '.TBA[].downloads.linux.link')
+    curl -Lv "${latest_jetbrains_toolbox}" -o "${TMP_DOT_FILES}/jetbrains-toolbox.tar.gz"
     tar -xzvf "${TMP_DOT_FILES}/jetbrains-toolbox.tar.gz" -C "${TMP_DOT_FILES}"
-    mv "${TMP_DOT_FILES}"/jetbrains-toolbox-*/jetbrains-toolbox "${HOME_BIN}/"
+    mv "${TMP_DOT_FILES}"/jetbrains-toolbox-*/jetbrains-toolbox "${home_bin}/"
   fi
 
   if ! grep -q 'Bourne-Again shell' <(file ~/.tmux/plugins/tpm/tpm); then
@@ -218,8 +242,6 @@ function install_desktop_apps() {
     mkdir -p ~/.tmux/plugins/tpm
     git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
   fi
-
-  rm -rf "${TMP_DOT_FILES}"
 }
 
 if ! /bin/grep -qi 'virtual' <(/bin/grep 'Product Name:' <(sudo dmidecode)); then
